# Generated by Django 5.1.5 on 2025-02-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report'),
        ),
        migrations.AlterField(
            model_name='part',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report'),
        ),
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report'),
        ),
    ]
