# Generated by Django 5.1.5 on 2025-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invoice_report_alter_part_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='quantity_used',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
