# Generated by Django 5.1.5 on 2025-04-25 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_owner_created_at_owner_updated_at_vehicle_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
