# Generated by Django 5.1.5 on 2025-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tasktemplate_created_at_tasktemplate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
