# Generated by Django 5.1.5 on 2025-05-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_inventory_quantity_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='unknow', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='noname', max_length=100),
            preserve_default=False,
        ),
    ]
