# Generated by Django 5.1.5 on 2025-05-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_full_name_owner_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.report'),
        ),
    ]
