"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# back/backend/settings/base.py -> back/backend/settings -> back/backend -> back
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Before any secret or setting is read, so back/.env can supply every one of
# them. It previously ran after read_secret(), which silently made three of the
# documented variables unusable from that file.
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Set the MySQL host
MYSQL_HOST = os.getenv("MYSQL_HOST")

# Path to the secrets directory (../secrets)
SECRETS_DIR = Path("/run/secrets")


def read_secret(filename, default=None, env=None):
    """Resolve a secret from the environment, then the Docker secrets mount.

    Production mounts Docker secrets at /run/secrets and sets none of these
    environment variables, so it still reads the files. The env fallback
    exists so CI and local development can run without a secrets mount -
    without it the test suite cannot even import settings.
    """
    if env:
        value = os.getenv(env)
        if value:
            return value
    try:
        return (SECRETS_DIR / filename).read_text().strip()
    except FileNotFoundError:
        if default is not None:
            return default
        raise Exception(
            f"Secret {filename} not found: set ${env} or mount {SECRETS_DIR / filename}"
            if env
            else f"Secret file {filename} not found in {SECRETS_DIR}"
        ) from None


def csv_env(name, default=""):
    """Parse a comma-separated environment variable into a list of strings.

    CORS_ALLOWED_ORIGINS was previously read as
    `os.getenv('CORS_ALLOWED_ORIGINS').split(',')`, which raises AttributeError
    on an unset variable - before Django starts, with no useful message.
    """
    raw = os.getenv(name, default) or ""
    return [item.strip() for item in raw.split(",") if item.strip()]


DJANGO_SECRET_KEY = read_secret("django_secret_key", env="DJANGO_SECRET_KEY")
MYSQL_USER = read_secret("mysql_user", env="MYSQL_USER")
MYSQL_PASSWORD = read_secret("mysql_password", env="MYSQL_PASSWORD")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DJANGO_SECRET_KEY

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    # Custom
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
}

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DATABASE"),
        "USER": MYSQL_USER,
        "PASSWORD": MYSQL_PASSWORD,
        "HOST": MYSQL_HOST,
        "PORT": os.getenv("MYSQL_PORT"),
        "TEST": {
            "NAME": f"test_{os.getenv('MYSQL_DATABASE')}",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "api.User"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static and Media files
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static_django/"

# In production
# Absolute container paths by default - /backend is the image WORKDIR and the
# mount point for the staticfiles and media volumes. Overridable so the test
# suite can run outside a container, where /backend does not exist and cannot
# be created. Production sets neither variable and therefore keeps these values.
STATIC_ROOT = os.getenv("STATIC_ROOT", "/backend/staticfiles")
MEDIA_ROOT = os.getenv("MEDIA_ROOT", "/backend/media")

STATICFILES_DIRS = [BASE_DIR / "static"]

# Media file path
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=20),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        # You can also add specific loggers for your app
        "myapiapp": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}
